version: '2'
services:
  mysql:
    # network_mode: myNetwork
    container_name: benz_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ''
      # MYSQL_USER: 'root'
      # MYSQL_PASS: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql